-- Insert sample products into the database
INSERT INTO products (name, category, image_url, new_price, old_price, description) VALUES
-- Women's products (12 items)
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', '/assets/StripedFlutter.jpg', 50.00, 80.50, 'Elegant striped blouse with flutter sleeves and peplum hem - perfect for casual and professional settings'),
('Floral Print Wrap Dress', 'women', '/assets/FloralPrintWrapDress.jpg', 85.00, 120.50, 'Beautiful floral wrap dress perfect for any occasion - comfortable and stylish'),
('Classic White Button-Down Shirt', 'women', '/assets/WhiteButton-Down.jpg', 60.00, 100.50, 'Timeless white shirt for professional look - versatile wardrobe essential'),
('Elegant Evening Gown', 'women', '/assets/ElegantEveningGown.jpg', 100.00, 150.00, 'Stunning evening gown for special events and celebrations'),
('Casual Summer Top', 'women', '/assets/CasualSummerTop.jpg', 45.00, 75.50, 'Light and breezy summer top - perfect for warm weather'),
('Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse', 'women', '/assets/StripedFlutter.jpg', 50.00, 80.50, 'Elegant striped blouse with flutter sleeves and peplum hem - perfect for casual and professional settings'),
('Floral Print Wrap Dress', 'women', '/assets/FloralPrintWrapDress.jpg', 85.00, 120.50, 'Beautiful floral wrap dress perfect for any occasion - comfortable and stylish'),
('Classic White Button-Down Shirt', 'women', '/assets/WhiteButton-Down.jpg', 60.00, 100.50, 'Timeless white shirt for professional look - versatile wardrobe essential'),
('Elegant Evening Gown', 'women', '/assets/ElegantEveningGown.jpg', 100.00, 150.00, 'Stunning evening gown for special events and celebrations'),
('Casual Summer Top', 'women', '/assets/CasualSummerTop.jpg', 45.00, 75.50, 'Light and breezy summer top - perfect for warm weather'),
('Striped Casual Blouse', 'women', '/assets/StripedCasualBlouse.jpg', 55.00, 90.50, 'Comfortable striped blouse for everyday wear with modern design'),
('Bohemian Style Dress', 'women', '/assets/BohemianDress.jpg', 75.00, 120.50, 'Free-spirited bohemian dress with unique patterns'),
('Professional Blazer', 'women', '/assets/ProfessionalBlazer.jpg', 95.00, 150.50, 'Tailored blazer for business settings and formal events'),
('Flowy Maxi Dress', 'women', '/assets/FlowyMaxiDress.jpg', 80.00, 130.50, 'Elegant flowy maxi dress for comfortable all-day wear'),
('Knitted Sweater', 'women', '/assets/KnittedSweater.jpg', 65.00, 110.50, 'Cozy knitted sweater for winter - soft and warm'),
('Trendy Crop Top', 'women', '/assets/TrendyCropTop.jpg', 40.00, 65.50, 'Modern crop top for casual outings and social gatherings'),
('Striped Casual Blouse', 'women', '/assets/StripedCasualBlouse.jpg', 55.00, 90.50, 'Comfortable striped blouse for everyday wear with modern design'),
('Bohemian Style Dress', 'women', '/assets/BohemianDress.jpg', 75.00, 120.50, 'Free-spirited bohemian dress with unique patterns'),
('Professional Blazer', 'women', '/assets/ProfessionalBlazer.jpg', 95.00, 150.50, 'Tailored blazer for business settings and formal events'),
('Flowy Maxi Dress', 'women', '/assets/FlowyMaxiDress.jpg', 80.00, 130.50, 'Elegant flowy maxi dress for comfortable all-day wear'),
('Knitted Sweater', 'women', '/assets/KnittedSweater.jpg', 65.00, 110.50, 'Cozy knitted sweater for winter - soft and warm'),
('Trendy Crop Top', 'women', '/assets/TrendyCropTop.jpg', 40.00, 65.50, 'Modern crop top for casual outings and social gatherings'),
('Striped Casual Blouse', 'women', '/assets/StripedCasualBlouse.jpg', 55.00, 90.50, 'Comfortable striped blouse for everyday wear with modern design'),
('Bohemian Style Dress', 'women', '/assets/BohemianDress.jpg', 75.00, 120.50, 'Free-spirited bohemian dress with unique patterns'),
('Professional Blazer', 'women', '/assets/ProfessionalBlazer.jpg', 95.00, 150.50, 'Tailored blazer for business settings and formal events'),
('Flowy Maxi Dress', 'women', '/assets/FlowyMaxiDress.jpg', 80.00, 130.50, 'Elegant flowy maxi dress for comfortable all-day wear'),
('Knitted Sweater', 'women', '/assets/KnittedSweater.jpg', 65.00, 110.50, 'Cozy knitted sweater for winter - soft and warm'),
('Trendy Crop Top', 'women', '/assets/TrendyCropTop.jpg', 40.00, 65.50, 'Modern crop top for casual outings and social gatherings'),
('Designer Blouse', 'women', '/assets/DesignerBlouse.jpg', 90.00, 145.50, 'Premium designer blouse with exquisite craftsmanship'),

-- Men's products (12 items)
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', '/assets/MenGreenBomberJacket.jpg', 85.00, 130.50, 'Stylish bomber jacket for modern men with sleek design'),
('Classic Denim Jacket', 'men', '/assets/ClassicDenimJacket.jpg', 75.00, 120.50, 'Timeless denim jacket - a wardrobe staple'),
('Casual Cotton T-Shirt', 'men', '/assets/CasualCottonT-Shirt.jpg', 30.00, 50.50, 'Comfortable everyday t-shirt in premium cotton'),
('Formal Dress Shirt', 'men', '/assets/FormalDressShirt.jpg', 70.00, 115.50, 'Elegant dress shirt for formal occasions and business'),
('Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket', 'men', '/assets/MenGreenBomberJacket.jpg', 85.00, 130.50, 'Stylish bomber jacket for modern men with sleek design'),
('Classic Denim Jacket', 'men', '/assets/ClassicDenimJacket.jpg', 75.00, 120.50, 'Timeless denim jacket - a wardrobe staple'),
('Casual Cotton T-Shirt', 'men', '/assets/CasualCottonT-Shirt.jpg', 30.00, 50.50, 'Comfortable everyday t-shirt in premium cotton'),
('Formal Dress Shirt', 'men', '/assets/FormalDressShirt.jpg', 70.00, 115.50, 'Elegant dress shirt for formal occasions and business'),
('Leather Jacket', 'men', '/assets/LeatherJacket.jpg', 150.00, 220.50, 'Premium leather jacket with superior quality'),
('Hooded Sweatshirt', 'men', '/assets/HoodedSweatshirt.jpg', 55.00, 95.50, 'Warm and comfortable hoodie for casual wear'),
('Slim Fit Jeans', 'men', '/assets/SlimFitJeans.jpg', 65.00, 110.50, 'Modern slim fit jeans with contemporary style'),
('Sports Jacket', 'men', '/assets/SportsJacket.jpg', 80.00, 130.50, 'Athletic sports jacket for active lifestyle'),
('Polo Shirt', 'men', '/assets/PoloShirt.jpg', 45.00, 75.50, 'Classic polo shirt in multiple colors'),
('Winter Coat', 'men', '/assets/WinterCoat.jpg', 120.00, 180.50, 'Warm winter coat for cold season protection'),
('Leather Jacket', 'men', '/assets/LeatherJacket.jpg', 150.00, 220.50, 'Premium leather jacket with superior quality'),
('Hooded Sweatshirt', 'men', '/assets/HoodedSweatshirt.jpg', 55.00, 95.50, 'Warm and comfortable hoodie for casual wear'),
('Slim Fit Jeans', 'men', '/assets/SlimFitJeans.jpg', 65.00, 110.50, 'Modern slim fit jeans with contemporary style'),
('Sports Jacket', 'men', '/assets/SportsJacket.jpg', 80.00, 130.50, 'Athletic sports jacket for active lifestyle'),
('Polo Shirt', 'men', '/assets/PoloShirt.jpg', 45.00, 75.50, 'Classic polo shirt in multiple colors'),
('Winter Coat', 'men', '/assets/WinterCoat.jpg', 120.00, 180.50, 'Warm winter coat for cold season protection'),
('Leather Jacket', 'men', '/assets/LeatherJacket.jpg', 150.00, 220.50, 'Premium leather jacket with superior quality'),
('Hooded Sweatshirt', 'men', '/assets/HoodedSweatshirt.jpg', 55.00, 95.50, 'Warm and comfortable hoodie for casual wear'),
('Slim Fit Jeans', 'men', '/assets/SlimFitJeans.jpg', 65.00, 110.50, 'Modern slim fit jeans with contemporary style'),
('Sports Jacket', 'men', '/assets/SportsJacket.jpg', 80.00, 130.50, 'Athletic sports jacket for active lifestyle'),
('Polo Shirt', 'men', '/assets/PoloShirt.jpg', 45.00, 75.50, 'Classic polo shirt in multiple colors'),
('Winter Coat', 'men', '/assets/WinterCoat.jpg', 120.00, 180.50, 'Warm winter coat for cold season protection'),
('Cargo Pants', 'men', '/assets/CargoPants.jpg', 70.00, 115.50, 'Practical cargo pants with multiple pockets'),
('Varsity Jacket', 'men', '/assets/VarsityJacket.jpg', 95.00, 150.50, 'Retro varsity jacket for classic style'),

-- Kids products (12 items)
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', '/assets/BoysOrangeSweatshirt.jpg', 45.00, 75.50, 'Vibrant hooded sweatshirt for active kids'),
('Kids Denim Jacket', 'kid', '/assets/kids-denim-jacket.jpg', 50.00, 85.50, 'Cute denim jacket for kids - durable and stylish'),
('Colorful T-Shirt', 'kid', '/assets/ColorfulT-Shirt.jpg', 25.00, 45.50, 'Fun and colorful t-shirt for everyday wear'),
('Kids Winter Jacket', 'kid', '/assets/KidsWinterJacket.jpg', 70.00, 115.50, 'Warm jacket for cold days - comfortable padding'),
('Boys Orange Colourblocked Hooded Sweatshirt', 'kid', '/assets/BoysOrangeSweatshirt.jpg', 45.00, 75.50, 'Vibrant hooded sweatshirt for active kids'),
('Kids Denim Jacket', 'kid', '/assets/kids-denim-jacket.jpg', 50.00, 85.50, 'Cute denim jacket for kids - durable and stylish'),
('Colorful T-Shirt', 'kid', '/assets/ColorfulT-Shirt.jpg', 25.00, 45.50, 'Fun and colorful t-shirt for everyday wear'),
('Kids Winter Jacket', 'kid', '/assets/KidsWinterJacket.jpg', 70.00, 115.50, 'Warm jacket for cold days - comfortable padding'),
('Striped Polo', 'kid', '/assets/StripedPolo.jpg', 35.00, 60.50, 'Stylish striped polo with classic design'),
('Casual Shorts Set', 'kid', '/assets/CasualShortsSet.jpg', 40.00, 70.50, 'Comfortable shorts set for summer activities'),
('Sports Tracksuit', 'kid', '/assets/SportsTracksuit.jpg', 55.00, 95.50, 'Athletic tracksuit for kids - perfect for sports'),
('Graphic Print Tee', 'kid', '/assets/GraphicPrintTee.jpg', 30.00, 50.50, 'Cool graphic print t-shirt with fun designs'),
('Kids Bomber Jacket', 'kid', '/assets/KidsBomberJacket.jpg', 60.00, 100.50, 'Trendy bomber jacket for kids'),
('Fleece Hoodie', 'kid', '/assets/FleeceHoodie.jpg', 50.00, 85.50, 'Soft fleece hoodie for warmth and comfort'),
('Striped Polo', 'kid', '/assets/StripedPolo.jpg', 35.00, 60.50, 'Stylish striped polo with classic design'),
('Casual Shorts Set', 'kid', '/assets/CasualShortsSet.jpg', 40.00, 70.50, 'Comfortable shorts set for summer activities'),
('Sports Tracksuit', 'kid', '/assets/SportsTracksuit.jpg', 55.00, 95.50, 'Athletic tracksuit for kids - perfect for sports'),
('Graphic Print Tee', 'kid', '/assets/GraphicPrintTee.jpg', 30.00, 50.50, 'Cool graphic print t-shirt with fun designs'),
('Kids Bomber Jacket', 'kid', '/assets/KidsBomberJacket.jpg', 60.00, 100.50, 'Trendy bomber jacket for kids'),
('Fleece Hoodie', 'kid', '/assets/FleeceHoodie.jpg', 50.00, 85.50, 'Soft fleece hoodie for warmth and comfort'),
('Striped Polo', 'kid', '/assets/StripedPolo.jpg', 35.00, 60.50, 'Stylish striped polo with classic design'),
('Casual Shorts Set', 'kid', '/assets/CasualShortsSet.jpg', 40.00, 70.50, 'Comfortable shorts set for summer activities'),
('Sports Tracksuit', 'kid', '/assets/SportsTracksuit.jpg', 55.00, 95.50, 'Athletic tracksuit for kids - perfect for sports'),
('Graphic Print Tee', 'kid', '/assets/GraphicPrintTee.jpg', 30.00, 50.50, 'Cool graphic print t-shirt with fun designs'),
('Kids Bomber Jacket', 'kid', '/assets/KidsBomberJacket.jpg', 60.00, 100.50, 'Trendy bomber jacket for kids'),
('Fleece Hoodie', 'kid', '/assets/FleeceHoodie.jpg', 50.00, 85.50, 'Soft fleece hoodie for warmth and comfort'),
('Denim Shorts', 'kid', '/assets/DenimShorts.jpg', 35.00, 60.50, 'Comfortable denim shorts for outdoor play'),
('Kids Windbreaker', 'kid', '/assets/KidsWindbreaker.jpg', 45.00, 75.50, 'Lightweight windbreaker for all seasons')
ON CONFLICT DO NOTHING;
